### ISSUE TITLE
能否制作一个Vimeo的图标？

### ISSUE THREAD

**Issue by aglent** [zealson/Zure#2]
vimeo视频网站的图标
谢谢！

**Comment by zealson** [comment]
已制作此图标
2019-8-30
v1.6.5
1.图标更名：SoftBank.png→SoftBank_Letter.png
2.调优图标：Apple.png、Spotify.png、Nexitally.png、TVB.png、ViuTV.png
3.新增图标：SoftBank.png、Netflix_Letter.png、Vimeo.png、YouTube_Music.png、TIDAL.png、NTT.png、GT.png、BBTEC.png、GIA.png
